insert into merit_badges (name, eagle_required, category) values

-- Arts & Hobbies
('Animation', false, 'Arts & Hobbies'),
('Architecture and Construction', false, 'Arts & Hobbies'),
('Art', false, 'Arts & Hobbies'),
('Astronomy', false, 'Arts & Hobbies'),
('Chess', false, 'Arts & Hobbies'),
('Cinematography', false, 'Arts & Hobbies'),
('Coin Collecting', false, 'Arts & Hobbies'),
('Collections', false, 'Arts & Hobbies'),
('Game Design', false, 'Arts & Hobbies'),
('Graphic Arts', false, 'Arts & Hobbies'),
('Indian Lore', false, 'Arts & Hobbies'),
('Inventing', false, 'Arts & Hobbies'),
('Leatherwork', false, 'Arts & Hobbies'),
('Model Design and Building', false, 'Arts & Hobbies'),
('Moviemaking', false, 'Arts & Hobbies'),
('Music', false, 'Arts & Hobbies'),
('Painting', false, 'Arts & Hobbies'),
('Photography', false, 'Arts & Hobbies'),
('Pottery', false, 'Arts & Hobbies'),
('Reading', false, 'Arts & Hobbies'),
('Sculpture', false, 'Arts & Hobbies'),
('Stamp Collecting', false, 'Arts & Hobbies'),
('Theater', false, 'Arts & Hobbies'),
('Wood Carving', false, 'Arts & Hobbies'),
('Woodwork', false, 'Arts & Hobbies'),

-- Citizenship
('Citizenship in the Community', true, 'Citizenship'),
('Citizenship in the Nation', true, 'Citizenship'),
('Citizenship in Society', true, 'Citizenship'),
('Citizenship in the World', true, 'Citizenship'),
('Public Speaking', false, 'Citizenship'),

-- Communication
('Communication', true, 'Communication'),
('Digital Technology', false, 'Communication'),
('Journalism', false, 'Communication'),
('Signs, Signals, and Codes', false, 'Communication'),

-- Emergency Preparedness
('Emergency Preparedness', true, 'Emergency Preparedness'),
('Fire Safety', false, 'Emergency Preparedness'),
('First Aid', true, 'Emergency Preparedness'),
('Lifesaving', true, 'Emergency Preparedness'),
('Safety', false, 'Emergency Preparedness'),
('Search and Rescue', false, 'Emergency Preparedness'),

-- Environment
('Bird Study', false, 'Environment'),
('Environmental Science', true, 'Environment'),
('Fish and Wildlife Management', false, 'Environment'),
('Fishing', false, 'Environment'),
('Fly Fishing', false, 'Environment'),
('Forestry', false, 'Environment'),
('Geology', false, 'Environment'),
('Insect Study', false, 'Environment'),
('Mammal Study', false, 'Environment'),
('Nature', false, 'Environment'),
('Oceanography', false, 'Environment'),
('Plant Science', false, 'Environment'),
('Reptile and Amphibian Study', false, 'Environment'),
('Soil and Water Conservation', false, 'Environment'),
('Sustainability', true, 'Environment'),
('Weather', false, 'Environment'),

-- Family Life
('Cooking', true, 'Family Life'),
('Family Life', true, 'Family Life'),
('Pets', false, 'Family Life'),

-- Health & Fitness
('Athletics', false, 'Health & Fitness'),
('Cycling', true, 'Health & Fitness'),
('Hiking', true, 'Health & Fitness'),
('Personal Fitness', true, 'Health & Fitness'),
('Sports', false, 'Health & Fitness'),
('Swimming', true, 'Health & Fitness'),
('Water Sports', false, 'Health & Fitness'),

-- Outdoors
('Backpacking', false, 'Outdoors'),
('Camping', true, 'Outdoors'),
('Canoeing', false, 'Outdoors'),
('Climbing', false, 'Outdoors'),
('Horsemanship', false, 'Outdoors'),
('Kayaking', false, 'Outdoors'),
('Motorboating', false, 'Outdoors'),
('Orienteering', false, 'Outdoors'),
('Rowing', false, 'Outdoors'),
('Small-Boat Sailing', false, 'Outdoors'),
('Snow Sports', false, 'Outdoors'),
('Whitewater', false, 'Outdoors'),
('Wilderness Survival', false, 'Outdoors'),

-- Personal Development
('American Cultures', false, 'Personal Development'),
('American Heritage', false, 'Personal Development'),
('American Labor', false, 'Personal Development'),
('Entrepreneurship', false, 'Personal Development'),
('Law', false, 'Personal Development'),
('Personal Management', true, 'Personal Development'),
('Salesmanship', false, 'Personal Development'),
('Scholarship', false, 'Personal Development'),
('Scouting Heritage', false, 'Personal Development'),

-- Science & Technology
('Aviation', false, 'Science & Technology'),
('Chemical Engineering', false, 'Science & Technology'),
('Chemistry', false, 'Science & Technology'),
('Electricity', false, 'Science & Technology'),
('Electronics', false, 'Science & Technology'),
('Energy', false, 'Science & Technology'),
('Engineering', false, 'Science & Technology'),
('Exploration', false, 'Science & Technology'),
('Nuclear Science', false, 'Science & Technology'),
('Programming', false, 'Science & Technology'),
('Radio', false, 'Science & Technology'),
('Robotics', false, 'Science & Technology'),
('Space Exploration', false, 'Science & Technology'),

-- Skills & Crafts
('American Business', false, 'Skills & Crafts'),
('Animal Science', false, 'Skills & Crafts'),
('Archaeology', false, 'Skills & Crafts'),
('Archery', false, 'Skills & Crafts'),
('Automotive Maintenance', false, 'Skills & Crafts'),
('Basketball', false, 'Skills & Crafts'),
('Bugling', false, 'Skills & Crafts'),
('Crime Prevention', false, 'Skills & Crafts'),
('Dentistry', false, 'Skills & Crafts'),
('Disabilities Awareness', false, 'Skills & Crafts'),
('Dog Care', false, 'Skills & Crafts'),
('Farm Mechanics', false, 'Skills & Crafts'),
('Fingerprinting', false, 'Skills & Crafts'),
('Gardening', false, 'Skills & Crafts'),
('Geography', false, 'Skills & Crafts'),
('Golf', false, 'Skills & Crafts'),
('Landscape Architecture', false, 'Skills & Crafts'),
('Medicine', false, 'Skills & Crafts'),
('Metalwork', false, 'Skills & Crafts'),
('Mining in Society', false, 'Skills & Crafts'),
('Plumbing', false, 'Skills & Crafts'),
('Public Health', false, 'Skills & Crafts'),
('Pulp and Paper', false, 'Skills & Crafts'),
('Railroading', false, 'Skills & Crafts'),
('Rifle Shooting', false, 'Skills & Crafts'),
('Shotgun Shooting', false, 'Skills & Crafts'),
('Skating', false, 'Skills & Crafts'),
('Surveying', false, 'Skills & Crafts'),
('Textile', false, 'Skills & Crafts'),
('Traffic Safety', false, 'Skills & Crafts'),
('Truck Transportation', false, 'Skills & Crafts'),
('Veterinary Medicine', false, 'Skills & Crafts'),
('Welding', false, 'Skills & Crafts');
